# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ayieko/Projects And Research/Python Projects/Github-Desktop/DesidnFiles/cloneRepoUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(619, 436)
        self.cloneTabWidget = QtWidgets.QTabWidget(Form)
        self.cloneTabWidget.setGeometry(QtCore.QRect(0, 0, 611, 391))
        self.cloneTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.cloneTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.cloneTabWidget.setDocumentMode(True)
        self.cloneTabWidget.setObjectName("cloneTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gitcomFilterEnt = QtWidgets.QLineEdit(self.tab)
        self.gitcomFilterEnt.setGeometry(QtCore.QRect(10, 10, 481, 33))
        self.gitcomFilterEnt.setText("")
        self.gitcomFilterEnt.setObjectName("gitcomFilterEnt")
        self.gitcomFilterBtn = QtWidgets.QPushButton(self.tab)
        self.gitcomFilterBtn.setGeometry(QtCore.QRect(500, 10, 100, 31))
        self.gitcomFilterBtn.setObjectName("gitcomFilterBtn")
        self.gitcomTableWidget = QtWidgets.QTableWidget(self.tab)
        self.gitcomTableWidget.setGeometry(QtCore.QRect(10, 50, 591, 231))
        self.gitcomTableWidget.setObjectName("gitcomTableWidget")
        self.gitcomTableWidget.setColumnCount(1)
        self.gitcomTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.gitcomTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gitcomTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gitcomTableWidget.setItem(0, 0, item)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 295, 191, 21))
        self.label_3.setObjectName("label_3")
        self.gitcomLocPathEnt = QtWidgets.QLineEdit(self.tab)
        self.gitcomLocPathEnt.setGeometry(QtCore.QRect(20, 320, 481, 31))
        self.gitcomLocPathEnt.setObjectName("gitcomLocPathEnt")
        self.gitcomLocPathBtn = QtWidgets.QPushButton(self.tab)
        self.gitcomLocPathBtn.setGeometry(QtCore.QRect(520, 320, 81, 31))
        self.gitcomLocPathBtn.setObjectName("gitcomLocPathBtn")
        self.cloneTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 581, 91))
        self.label.setObjectName("label")
        self.urlCloneEnt = QtWidgets.QLineEdit(self.tab_2)
        self.urlCloneEnt.setGeometry(QtCore.QRect(10, 130, 581, 33))
        self.urlCloneEnt.setText("")
        self.urlCloneEnt.setObjectName("urlCloneEnt")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 361, 31))
        self.label_2.setObjectName("label_2")
        self.urlLocPathEnt = QtWidgets.QLineEdit(self.tab_2)
        self.urlLocPathEnt.setGeometry(QtCore.QRect(10, 250, 491, 33))
        self.urlLocPathEnt.setText("")
        self.urlLocPathEnt.setObjectName("urlLocPathEnt")
        self.urlLocPathBtn = QtWidgets.QPushButton(self.tab_2)
        self.urlLocPathBtn.setGeometry(QtCore.QRect(509, 250, 81, 31))
        self.urlLocPathBtn.setObjectName("urlLocPathBtn")
        self.cloneTabWidget.addTab(self.tab_2, "")
        self.cloneBtn = QtWidgets.QPushButton(Form)
        self.cloneBtn.setGeometry(QtCore.QRect(320, 400, 100, 31))
        self.cloneBtn.setObjectName("cloneBtn")
        self.cancelBtn = QtWidgets.QPushButton(Form)
        self.cancelBtn.setGeometry(QtCore.QRect(470, 400, 100, 31))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(Form)
        self.cloneTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Clone A Repository"))
        self.gitcomFilterEnt.setPlaceholderText(_translate("Form", "Filter Your Repositories"))
        self.gitcomFilterBtn.setText(_translate("Form", "Filter"))
        item = self.gitcomTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Your Repositories."))
        __sortingEnabled = self.gitcomTableWidget.isSortingEnabled()
        self.gitcomTableWidget.setSortingEnabled(False)
        item = self.gitcomTableWidget.item(0, 0)
        item.setText(_translate("Form", "ayieko168/Tv-Shows"))
        self.gitcomTableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Form", "Local Path"))
        self.gitcomLocPathEnt.setPlaceholderText(_translate("Form", "C:\\User\\..."))
        self.gitcomLocPathBtn.setText(_translate("Form", "Choose..."))
        self.cloneTabWidget.setTabText(self.cloneTabWidget.indexOf(self.tab), _translate("Form", "GitHub.com"))
        self.label.setText(_translate("Form", "<html><head/><body><p>Repository URL or GitHub username and respository</p><p><span style=\" font-style:italic;\">(Example: tom/cool-repo)</span></p></body></html>"))
        self.urlCloneEnt.setPlaceholderText(_translate("Form", "URL or username/repository"))
        self.label_2.setText(_translate("Form", "Local path :"))
        self.urlLocPathEnt.setPlaceholderText(_translate("Form", "C:\\User\\..."))
        self.urlLocPathBtn.setText(_translate("Form", "Choose..."))
        self.cloneTabWidget.setTabText(self.cloneTabWidget.indexOf(self.tab_2), _translate("Form", "URL"))
        self.cloneBtn.setText(_translate("Form", "Clone"))
        self.cancelBtn.setText(_translate("Form", "Cancel"))
